#include <sys/types.h> 
#include <stdio.h> 
#include <stdlib.h>
#include "fcgi_config.h" 
#include "fcgiapp.h" 
#include <fcgi_stdio.h>
#include <string.h>
#include <mysql/mysql.h>
#include <malloc.h>
